project:
  type: website
  output-dir: docs
  pre-render: "python3 gerar_posts_json.py"

website:
  title: "Romance da MatemÃ¡tica"
  favicon: images/banner.jpeg
  site-url: https://marcellini-celso.github.io/romance-matematica-em/index.html

  navbar:
    left:
      - href: index.qmd
        text: InÃ­cio
      - href: tags.qmd
        text: "ðŸ·ï¸ Tags"
      - href: categories.qmd
        text: "ðŸ“‚ Categorias"
      - text: "ðŸ§  CapÃ­tulos"
        menu:
          - text: "ðŸ§® CapÃ­tulo 1"
            href: posts/capitulos/cap1-funcao-quadratica.qmd
          - text: "ðŸ“Š CapÃ­tulo 2"
            href: posts/capitulos/cap2-numeros-conjuntos.qmd
          - text: "ðŸ”­ CapÃ­tulo 3"
            href: posts/capitulos/cap3-conjuntos.qmd
      - text: "ðŸ“ Sobre"
        menu:
          - text: "ðŸ‘¤ Sobre Mim e Sobre o Blog"
            href: posts/sobre/sobre-o-blog.qmd
      - href: guia.qmd
        text: "ðŸ—ºï¸ Mapa do Site"
    right:
      - icon: envelope
        text: "Contato"
        href: "mailto:prof.marcellini@gmail.com"

  page-footer:
    left: "Â© 2025 - Romance da MatemÃ¡tica: Aventuras no Ensino MÃ©dio"
    right: >
      ðŸ“¬ [Contato por E-mail](mailto:prof.marcellini@gmail.com)<br>
      ðŸ’» <a href="https://github.com/marcellini-celso/romance-matematica-em.git" target="_blank">GitHub do Projeto</a>

format:
  html:
    theme: cosmo
    css:
      - styles.css
      - assets/css/custom.css
    toc: true
    toc-location: right
    toc-title: "Nesta pÃ¡gina"
    code-copy: true
    highlight-style: github
    include-in-header: analytics.html

search: true

publish:
  provider: gh-pages

resources:
  - posts.json

